//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyberarms.IntrusionDetection.Shared {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyberarms.IntrusionDetection.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap agent15px_custom_dark {
            get {
                object obj = ResourceManager.GetObject("agent15px_custom_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap agent15px_custom_white {
            get {
                object obj = ResourceManager.GetObject("agent15px_custom_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap agent15px_default_dark {
            get {
                object obj = ResourceManager.GetObject("agent15px_default_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap agent15px_default_white {
            get {
                object obj = ResourceManager.GetObject("agent15px_default_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似                                                     
        ///                                                    &lt;tr style=&quot;mso-yfti-irow:2&quot;&gt;
        ///                                                        &lt;td style=&quot;padding:3.75pt 0cm 3.75pt 3.75pt; text-align:left;&quot;&gt;
        ///                                                            &lt;p class=&quot;MsoNormal&quot;&gt;
        ///                                                                
        ///                                                                &lt;span style=&quot;font-size:10.5pt;font-family: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EventsPerAgent {
            get {
                return ResourceManager.GetString("EventsPerAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       &lt;tr style=&quot;mso-yfti-irow:2&quot;&gt;
        ///                                                        &lt;td style=&quot;padding:3.75pt 0cm 3.75pt 3.75pt; text-align:left;&quot;&gt;
        ///                                                            &lt;p class=&quot;MsoNormal&quot;&gt;
        ///                                                                
        ///                                                                &lt;span style=&quot;font-size:10.5pt;font-family:
        ///        &amp;quot;Helvetica&amp;quot;,&amp;quot;sans-serif&amp;quot;;mso-fareast-font-family:&amp;quot;Times New Roman [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HardLocksByIp {
            get {
                return ResourceManager.GetString("HardLocksByIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       
        ///                                                    &lt;tr style=&quot;mso-yfti-irow:2&quot;&gt;
        ///                                                        &lt;td style=&quot;padding:3.75pt 0cm 3.75pt 3.75pt; text-align:left;&quot;&gt;
        ///                                                            &lt;p class=&quot;MsoNormal&quot;&gt;
        ///                                                                
        ///                                                                &lt;span style=&quot;font-size:10.5pt;font-family:&amp;quot;Helvetica&amp;quot;,&amp;quot;sans-serif&amp;quot;;m [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IntrusionAttemptsByIp {
            get {
                return ResourceManager.GetString("IntrusionAttemptsByIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_hardLock {
            get {
                object obj = ResourceManager.GetObject("logIcon_hardLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_loginAttempt {
            get {
                object obj = ResourceManager.GetObject("logIcon_loginAttempt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_softLock {
            get {
                object obj = ResourceManager.GetObject("logIcon_softLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_systemMessage {
            get {
                object obj = ResourceManager.GetObject("logIcon_systemMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_unlock {
            get {
                object obj = ResourceManager.GetObject("logIcon_unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap logIcon_warning {
            get {
                object obj = ResourceManager.GetObject("logIcon_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///        
        ///        &lt;!-- Facebook sharing information tags --&gt;
        ///        &lt;meta property=&quot;og:title&quot; content=&quot;[%TITLE%]&quot; /&gt;
        ///        
        ///        &lt;title&gt;[%TITLE%]&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///
        /// p.MsoNormal
        ///  {margin-bottom:.0001pt;
        ///  font-size:12.0pt;
        ///  font-family:&quot;Times New Roman&quot;,&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ReportTemplate {
            get {
                return ResourceManager.GetString("ReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tr style=&quot;mso-yfti-irow:2&quot;&gt;
        ///                                                        &lt;td style=&quot;padding:3.75pt 0cm 3.75pt 3.75pt; text-align:left;&quot;&gt;
        ///                                                            &lt;p class=&quot;MsoNormal&quot;&gt;
        ///                                                                
        ///                                                                &lt;span style=&quot;font-size:10.5pt;font-family:
        ///        &amp;quot;Helvetica&amp;quot;,&amp;quot;sans-serif&amp;quot;;mso-fareast-font-family:&amp;quot;Times New Roman&amp;quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SoftLocksByIp {
            get {
                return ResourceManager.GetString("SoftLocksByIp", resourceCulture);
            }
        }
    }
}
